spring.application.name=velaroute

# Database Connection
spring.datasource.url = jdbc:postgresql://localhost:5432/velaroute
spring.datasource.username = xndr
spring.datasource.password = LeonGRC2025!

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect